### ISSUE TITLE
Minor syntax errors

### ISSUE THREAD

**Issue by Mahmoud-A-Yehia** [ahmedabougabal/DatabaseManagementSystem_ITI#3]
There are some minor syntax errors I found in your code,  pls address them 
No worries, they are just some spaces you missed which cause unexpected behaviour,  rest of the code is fine

**Comment by ahmedabougabal** [comment]
Thanks for informing, I will fix them ASAP.

**Comment by ahmedabougabal** [comment]
***Everything related to this issue has been resolved.***
